# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'conscious' do
  pod 'EZAudio', '~> 1.0'
  pod 'MMParallaxCell'
  pod 'TEAChart', '~> 0.3.2'
  pod 'DynamicColor', '~> 2.4.0'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
end

